const $=s=>document.querySelector(s),state={proxies:[]};
async function api(path,options){const r=await fetch(path,options),d=await r.json();if(!r.ok)throw Error(d.error||'请求失败');return d}
const credKey=t=>t==='vless'?'uuid':'password';
const selVal=h=>h.type==='socks'?'socks5':(h.type==='http'&&h.tls?'https':h.type);
const credFields=(h,i,dc)=>(h.type==='socks'||h.type==='http')?`<label>用户名<input data-k="username" data-i="${i}"${dc} value="${h.username||''}"></label><label>密码<input data-k="password" data-i="${i}"${dc} value="${h.password||''}"></label>`:`<label>凭据<input data-k="${credKey(h.type)}" data-i="${i}"${dc} value="${h[credKey(h.type)]||''}"></label>`;
function grid(h,i,c){const dc=c===undefined?'':` data-c="${c}"`;return `<div class="proxy-grid"><label>名称<input data-k="name" data-i="${i}"${dc} value="${h.name||''}"></label><label>类型<select data-k="type" data-i="${i}"${dc}><option ${selVal(h)==='ss'?'selected':''}>ss</option><option ${selVal(h)==='vless'?'selected':''}>vless</option><option ${selVal(h)==='trojan'?'selected':''}>trojan</option><option ${selVal(h)==='socks5'?'selected':''}>socks5</option><option ${selVal(h)==='http'?'selected':''}>http</option><option ${selVal(h)==='https'?'selected':''}>https</option></select></label>${c===undefined?`<label>本地端口<input data-k="localPort" data-i="${i}" type="number" value="${h.localPort||''}"></label>`:''}<label>远端地址<input data-k="address" data-i="${i}"${dc} value="${h.address||''}"></label><label>远端端口<input data-k="port" data-i="${i}"${dc} type="number" value="${h.port||''}"></label>${credFields(h,i,dc)}<label>加密方式 / 网络<input data-k="${h.type==='ss'?'method':'network'}" data-i="${i}"${dc} value="${h[h.type==='ss'?'method':'network']||''}" placeholder="${h.type==='ss'?'aes-128-gcm':'tcp'}"></label></div>`}
function render(){$('#proxies').innerHTML=state.proxies.map((p,i)=>{const chain=p.chain||[];return `<div class="proxy"><div class="hop-head"><span class="hop-tag">入口</span><button class="remove" data-i="${i}">删除</button></div>${grid(p,i)}${chain.map((h,c)=>`<div class="hop"><div class="hop-head"><span class="hop-tag">第 ${c+2} 跳${c===chain.length-1?' · 出口':''}</span><button class="remove" data-i="${i}" data-c="${c}">删除</button></div>${grid(h,i,c)}</div>`).join('')}<button class="ghost add-hop" data-i="${i}">＋ 添加出口节点</button></div>`}).join('')}
function collect(){document.querySelectorAll('[data-k]').forEach(e=>{let v=e.value;const p=state.proxies[+e.dataset.i];if(!p)return;const o=e.dataset.c!==undefined?(p.chain&&p.chain[+e.dataset.c]):p;if(!o)return;if(e.dataset.k==='type'){if(v!==selVal(o))o.tls=v==='https';if(v==='socks5')v='socks';else if(v==='https')v='http'}if(['port','localPort'].includes(e.dataset.k))v=+v;o[e.dataset.k]=v})}
function update(s){$('#status').className='status '+(s.running?'on':'');$('#status').innerHTML=`<i></i>${s.running?'运行中':'已停止'}`;$('#toggle').textContent=s.running?'停止 Xray':'启动 Xray'}
async function refresh(){const [c,s]=await Promise.all([api('/api/config'),api('/api/status')]);Object.assign(state,c);render();update(s)}
const uriList=()=>$('#uri').value.split(/\s+/).filter(Boolean);
$('#add').onclick=()=>{state.proxies.push({name:`节点 ${state.proxies.length+1}`,type:'vless',localPort:1080+state.proxies.length,address:'',port:443,network:'tcp'});render()};
$('#proxies').onclick=e=>{const t=e.target;if(t.className.includes('remove')){const i=+t.dataset.i;if(t.dataset.c!==undefined)state.proxies[i].chain.splice(+t.dataset.c,1);else state.proxies.splice(i,1);render()}else if(t.className.includes('add-hop')){const p=state.proxies[+t.dataset.i];p.chain=p.chain||[];p.chain.push({name:`出口 ${p.chain.length+1}`,type:'socks',address:'',port:1080,network:'tcp'});render()}};
$('#proxies').onchange=e=>{if(e.target.tagName==='SELECT'&&e.target.dataset.k==='type'){collect();render()}};
$('#parse').onclick=async()=>{try{const us=uriList();if(!us.length)throw Error('请输入 URI');const p=await api('/api/parse',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({uris:us})});p.localPort=1080+state.proxies.length;state.proxies.push(p);render();$('#test-message').textContent=us.length>1?`已解析 ${us.length} 跳链式转发，请保存配置`:'已解析，请保存配置'}catch(e){$('#test-message').textContent=e.message}};
$('#test-uri').onclick=async()=>{try{const us=uriList();if(!us.length)throw Error('请输入 URI');const r=await api('/api/test',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(us.length>1?{uris:us}:{uri:us[0]})});$('#test-message').textContent=r.ok?`连通，HTTP ${r.status}，${r.latencyMs}ms`:`无法连通，仍可保存${r.error?': '+r.error:''}`}catch(e){$('#test-message').textContent=e.message}};
$('#save').onclick=async()=>{try{collect();await api('/api/config',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(state)});$('#message').textContent='配置已保存'}catch(e){$('#message').textContent=e.message}};
$('#toggle').onclick=async()=>{try{const s=await api($('#toggle').textContent[0]==='启'?'/api/start':'/api/stop',{method:'POST'});update(s)}catch(e){$('#message').textContent=e.message}};refresh().catch(e=>$('#message').textContent=e.message);
