const $=s=>document.querySelector(s),state={proxies:[]};
async function api(path,options){const r=await fetch(path,options),d=await r.json();if(!r.ok)throw Error(d.error||'请求失败');return d}
function render(){ $('#proxies').innerHTML=state.proxies.map((p,i)=>`<div class="proxy"><button class="remove" data-i="${i}">删除</button><div class="proxy-grid"><label>名称<input data-k="name" data-i="${i}" value="${p.name||''}"></label><label>类型<select data-k="type" data-i="${i}"><option ${p.type==='ss'?'selected':''}>ss</option><option ${p.type==='vless'?'selected':''}>vless</option><option ${p.type==='trojan'?'selected':''}>trojan</option></select></label><label>本地端口<input data-k="localPort" data-i="${i}" type="number" value="${p.localPort||''}"></label><label>远端地址<input data-k="address" data-i="${i}" value="${p.address||''}"></label><label>远端端口<input data-k="port" data-i="${i}" type="number" value="${p.port||''}"></label><label>凭据<input data-k="${p.type==='vless'?'uuid':'password'}" data-i="${i}" value="${p[p.type==='vless'?'uuid':'password']||''}"></label><label>加密方式 / 网络<input data-k="${p.type==='ss'?'method':'network'}" data-i="${i}" value="${p[p.type==='ss'?'method':'network']||''}" placeholder="${p.type==='ss'?'aes-128-gcm':'tcp'}"></label></div></div>`).join('')}
function collect(){document.querySelectorAll('[data-k]').forEach(e=>{let v=e.value;if(['port','localPort'].includes(e.dataset.k))v=+v;state.proxies[+e.dataset.i][e.dataset.k]=v})}
function update(s){$('#status').className='status '+(s.running?'on':'');$('#status').innerHTML=`<i></i>${s.running?'运行中':'已停止'}`;$('#toggle').textContent=s.running?'停止 Xray':'启动 Xray'}
async function refresh(){const [c,s]=await Promise.all([api('/api/config'),api('/api/status')]);Object.assign(state,c);render();update(s)}
$('#add').onclick=()=>{state.proxies.push({name:`节点 ${state.proxies.length+1}`,type:'vless',localPort:1080+state.proxies.length,address:'',port:443,network:'tcp'});render()};
$('#proxies').onclick=e=>{if(e.target.className==='remove'){state.proxies.splice(+e.target.dataset.i,1);render()}};
$('#parse').onclick=async()=>{try{const p=await api('/api/parse',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({uri:$('#uri').value})});p.localPort=1080+state.proxies.length;state.proxies.push(p);render();$('#test-message').textContent='已解析，请保存配置'}catch(e){$('#test-message').textContent=e.message}};
$('#test-uri').onclick=async()=>{try{const p=await api('/api/test',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({uri:$('#uri').value})});$('#test-message').textContent=p.ok?`连通，HTTP ${p.status}，${p.latencyMs}ms`:`无法连通，仍可保存${p.error?': '+p.error:''}`}catch(e){$('#test-message').textContent=e.message}};
$('#save').onclick=async()=>{try{collect();await api('/api/config',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(state)});$('#message').textContent='配置已保存'}catch(e){$('#message').textContent=e.message}};
$('#toggle').onclick=async()=>{try{const s=await api($('#toggle').textContent[0]==='启'?'/api/start':'/api/stop',{method:'POST'});update(s)}catch(e){$('#message').textContent=e.message}};refresh().catch(e=>$('#message').textContent=e.message);
